site_name: Tad Diary
theme:
  name: material
  logo: assets/logo/cat_white.png
  text: Noto Serif Medium
  code: Roboto Mono Medium
  highlightjs: true
  hljs_style: github
  hljs_style_dark: github-dark
  palette:
  - scheme: default
    primary: blue grey
    accent: pink
    toggle:
      icon: material/brightness-4
      name: Switch to dark mode
  - scheme: slate
    primary: blue grey
    accent: pink
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.tracking

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

nav:
  - Diary:
    - Note: index.md
    - Năm 2025:
      - Tháng 9: 2025/2025-9.md
      - Tháng 8: 2025/2025-8.md
      - Tháng 7: 2025/2025-7.md
      - Tháng 6: 2025/2025-6.md
  - Cuisine:
    - Tổng quan: Cuisine/cuisine.md
    - Thịt:
      - Gà: Cuisine/cuisine-meat-chicken.md
    - Đồ uống:
      - Trà: Cuisine/cuisine-tea.md
      - Cafe: Cuisine/cuisine-coffee.md
    - Dinh dưỡng:
      - Tổng quan: Cuisine/cuisine-nutrition.md
  - Mặt hàng:
    - Bàn phím: Items/items-keyboards.md
extra_css:
  - assets/stylesheets/theme.css
  - assets/stylesheets/katex.min.css
  # - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_javascript:
  - assets/scripts/katex.js
  - assets/scripts/keyevent.js
  - assets/scripts/katex.min.js
  - assets/scripts/auto-render.min.js
  # - https://unpkg.com/katex@0/dist/katex.min.js
  # - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dothanhdathp
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/tad.zeila?locale=vi_VN
